// GROCERY LIST CONSTANTS
export const LIST_REMOVE = 'LIST_REMOVE';
export const ADD_MISSING = 'ADD_MISSING';
export const TOGGLE_DONE = 'TOGGLE_DONE';
export const LIST_ADD = 'LIST_ADD';
// RECIPE LIST CONSTANTS
export const FETCH_RECIPES_REQUEST = 'FETCH_RECIPES_REQUEST';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';
// USER CONSTANTS